import AccountSelector from '../components/common/AccountSelector';
import { fetchAccountRecord } from '../services/accountService';
import { handleEnterNavigation } from '../utils/enterNavigation';
import DoneBySelect from '../components/common/DoneBySelect';
import { useEffect, useMemo, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import Card from '../components/common/Card';
import Button from '../components/common/Button';
import SearchableSelect from '../components/common/SearchableSelect';
import {
  FormCheckbox,
  FormInput,
  FormSelect,
  FormTextarea,
} from '../components/common/FormField';
import { useToast } from '../context/ToastContext';
import { fetchItems } from '../services/itemService';
import {
  createQuotation,
  fetchQuotationById,
  updateQuotation,
} from '../services/quotationService';
import { extractErrorMessage } from '../services/api';
import { saveDraft, loadDraft, clearDraft } from '../utils/draftStorage';
import { UNIT_OPTIONS } from '../config/units';
import {
  computeLineAmounts,
  computeTotals,
  formatCurrency,
} from '../utils/calculations';
import '../styles/PurchaseEntry.css';
import '../styles/SalesEntry.css';

const today = () => new Date().toISOString().slice(0, 10);

const STATES = [
  '',
  'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chhattisgarh',
  'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jharkhand', 'Karnataka',
  'Kerala', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram',
  'Nagaland', 'Odisha', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
  'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal',
  'Andaman and Nicobar Islands', 'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu', 'Delhi', 'Jammu and Kashmir',
  'Ladakh', 'Lakshadweep', 'Puducherry',
];

const STATE_OPTIONS = STATES.map((value) => ({
  value,
  label: value || 'Select State',
}));


const createEmptyDetails = () => ({
  customer_id: null,
  quotation_no: '',
  order_no: '',
  quotation_date: today(),
  due_term: '',
  due_date: '',
  is_gst: true,
  address: '',
  city: '',
  customer_state: '',
  contact_no: '',
  email: '',
  done_by: '',
  brokerage: 0,
  broker_remarks: '',
  delivery_date: '',
  ship_to: '',
  ship_to_address: '',
  ship_state: '',
  transport: '',
  reference: '',
  remarks: '',
  show_shipping_address_on_bill: false,
});

const createEmptyItem = () => ({
  item_id: null,
  item_name: '',
  hsn_code: '',
  quantity: '',
  unit: UNIT_OPTIONS[0]?.value || 'Box',
  price: '',
  current_stock: '',
  disc_percent: 0,
  sgst: 0,
  cgst: 0,
  igst: 0,
});

const getCustomerId = (customer) => customer?.id ?? customer?.customer_id ?? null;
const getItemId = (item) => item?.id ?? item?.item_id ?? null;

let rowCounter = 0;

function addDays(dateString, daysValue) {
  if (!dateString || daysValue === '' || Number(daysValue) < 0) return '';
  const date = new Date(`${dateString}T00:00:00`);
  date.setDate(date.getDate() + Number(daysValue));
  return date.toISOString().slice(0, 10);
}

export default function QuotationEntry() {
  const toast = useToast();
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const newCustomerId = searchParams.get('newCustomerId');
  const newItemId = searchParams.get('newItemId');
  const editId = searchParams.get('edit');
  const loadedEditId = useRef(null);
  const DRAFT_KEY = 'quotation-entry';

  const [itemRecords, setItemRecords] = useState([]);
  const [details, setDetails] = useState(createEmptyDetails);
  const [itemForm, setItemForm] = useState(createEmptyItem);
  const [items, setItems] = useState([]);
  const [detailErrors, setDetailErrors] = useState({});
  const [itemErrors, setItemErrors] = useState({});
  const [editingIndex, setEditingIndex] = useState(null);
  const [saving, setSaving] = useState(false);
  const [loadingQuotation, setLoadingQuotation] = useState(false);

  const loadItems = () => fetchItems({ search: '' })
    .then((data) => setItemRecords(data.filter((item) => item.is_active !== false)))
    .catch((error) => toast.error(extractErrorMessage(error)));

  useEffect(() => {
    loadItems();
    // Quotation No. and Order No. are generated by the backend when saving.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Restores a draft saved right before a "+ Add Customer/Item" redirect,
  // so returning here doesn't lose whatever was already filled in.
  // Skipped in edit mode since that flow loads from the server instead.
  useEffect(() => {
    if (editId) return;
    const draft = loadDraft(DRAFT_KEY);
    if (!draft) return;
    setDetails(draft.details);
    setItems(draft.items);
    setItemForm(draft.itemForm);
    clearDraft(DRAFT_KEY);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Fills in the newly created customer's contact info onto the draft
  // without wiping the items -- unlike selectCustomer(), this runs after
  // returning from "+ Add Customer" and should continue the same quotation.
  useEffect(() => {
    if (!newCustomerId) return;
    fetchAccountRecord('customer', newCustomerId)
      .then((full) => {
        setDetails((previous) => ({
          ...previous,
          _account: full,
          customer_id: getCustomerId(full),
          address: full?.address || '',
          city: full?.city || '',
          customer_state: full?.state || '',
          contact_no: full?.mobile || '',
          email: full?.email || '',
        }));
      })
      .catch((error) => toast.error(extractErrorMessage(error)));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [newCustomerId]);

  // Fills the item entry form with the newly created item -- the user
  // still picks quantity/price and clicks "Add" like any other item.
  useEffect(() => {
    if (!newItemId || !itemRecords.length) return;
    const item = itemRecords.find((row) => Number(getItemId(row)) === Number(newItemId));
    if (!item) return;
    selectItem({ value: getItemId(item), record: item });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [newItemId, itemRecords]);

  useEffect(() => {
    if (
      !editId
      || !itemRecords.length
      || loadedEditId.current === editId
    ) return;

    loadedEditId.current = editId;
    setLoadingQuotation(true);

    fetchQuotationById(editId)
      .then(async (quotation) => {
        const customer = await fetchAccountRecord('customer', quotation.customer_id, quotation);

        setDetails({
          _account: customer,
          customer_id: quotation.customer_id ?? null,
          quotation_no: quotation.quotation_no || '',
          order_no: quotation.order_no || '',
          quotation_date: quotation.quotation_date || today(),
          due_term: quotation.due_term ?? '',
          due_date: quotation.due_date || '',
          is_gst: quotation.is_gst !== false,
          address: quotation.address || customer?.address || '',
          city: quotation.city || customer?.city || '',
          customer_state: quotation.customer_state || quotation.state || customer?.state || '',
          contact_no: quotation.contact_no || customer?.mobile || '',
          email: quotation.email || customer?.email || '',
          done_by: quotation.done_by || '',
          _savedDoneBy: quotation.done_by || '',
          brokerage: quotation.brokerage ?? 0,
          broker_remarks: quotation.broker_remarks || '',
          delivery_date: quotation.delivery_date || '',
          ship_to: quotation.ship_to || '',
          ship_to_address: quotation.ship_to_address || '',
          ship_state: quotation.shipping_state || quotation.state || '',
          transport: quotation.transport || '',
          reference: quotation.reference || '',
          remarks: quotation.remarks || '',
          show_shipping_address_on_bill: Boolean(
            quotation.show_shipping_address_on_bill,
          ),
        });

        setItems((quotation.items || []).map((row) => {
          const master = itemRecords.find(
            (item) => Number(item.id) === Number(row.item_id),
          );

          return {
            _rowId: ++rowCounter,
            item_id: row.item_id,
            item_name: row.item_name || master?.name || '',
            hsn_code: row.hsn_code || master?.hsn_code || '',
            quantity: row.quantity ?? '',
            unit: row.unit || master?.unit || UNIT_OPTIONS[0]?.value || 'Box',
            price: row.rate ?? row.price ?? master?.sale_price ?? '',
            current_stock: master?.current_stock ?? row.current_stock ?? 0,
            disc_percent: row.disc_percent ?? 0,
            sgst: row.sgst ?? 0,
            cgst: row.cgst ?? 0,
            igst: row.igst ?? 0,
          };
        }));
      })
      .catch((error) => {
        toast.error(extractErrorMessage(error));
        navigate('/quotation-history');
      })
      .finally(() => setLoadingQuotation(false));
  }, [editId, itemRecords, navigate, toast]);

  const itemOptions = useMemo(
    () => itemRecords.map((item) => ({
      value: getItemId(item),
      label: item.name,
      meta: item.hsn_code ? `HSN ${item.hsn_code}` : 'HSN not set',
      record: item,
    })),
    [itemRecords],
  );

  const calculationItems = useMemo(
    () => (
      details.is_gst
        ? items
        : items.map((item) => ({
            ...item,
            sgst: 0,
            cgst: 0,
            igst: 0,
          }))
    ),
    [items, details.is_gst],
  );

  const calculationItemForm = useMemo(
    () => (
      details.is_gst
        ? itemForm
        : {
            ...itemForm,
            sgst: 0,
            cgst: 0,
            igst: 0,
          }
    ),
    [itemForm, details.is_gst],
  );

  const totals = useMemo(
    () => computeTotals(calculationItems),
    [calculationItems],
  );

  const liveAmount = useMemo(
    () => computeLineAmounts(calculationItemForm).amount,
    [calculationItemForm],
  );

  const changeDetail = (field, value) => {
    setDetails((previous) => {
      const next = { ...previous, [field]: value };
      if (field === 'quotation_date' || field === 'due_term') {
        next.due_date = addDays(
          field === 'quotation_date' ? value : previous.quotation_date,
          field === 'due_term' ? value : previous.due_term,
        );
      }
      return next;
    });

    setDetailErrors((previous) => ({ ...previous, [field]: '' }));
  };

  const applySelectedCustomer = (customer) => {
    setDetails((previous) => ({
      ...previous,
      _account: customer,
      customer_id: getCustomerId(customer),
      address: customer?.address || '',
      city: customer?.city || '',
      customer_state: customer?.state || '',
      contact_no: customer?.mobile || '',
      email: customer?.email || '',
      delivery_date: '',
      ship_to: '',
      ship_to_address: '',
      ship_state: '',
      transport: '',
      reference: '',
      remarks: '',
      show_shipping_address_on_bill: false,
    }));

    setItems([]);
    setItemForm(createEmptyItem());
    setEditingIndex(null);
    setItemErrors({});
  };

  const selectCustomer = (option) => {
    const nextId = option?.value ?? null;
    const currentId = details.customer_id ?? null;

    if (String(nextId ?? '') === String(currentId ?? '')) return;

    if (nextId == null || nextId === '') {
      applySelectedCustomer(null);
      return;
    }

    applySelectedCustomer(option.record);
    toast.success('Customer changed. Items and delivery details were cleared.');
  };

  const selectItem = (option) => {
    if (!option) {
      setItemForm(createEmptyItem());
      return;
    }

    const item = option.record;
    setItemForm((previous) => ({
      ...previous,
      item_id: getItemId(item),
      item_name: item.name,
      hsn_code: item.hsn_code || '',
      unit: item.unit || previous.unit,
      price: item.sale_price ?? previous.price,
      current_stock: item.current_stock ?? 0,
      cgst: item.cgst ?? 0,
      sgst: item.sgst ?? 0,
      igst: 0,
    }));

    setItemErrors({});
  };

  const changeItem = (field, value) => {
    setItemForm((previous) => {
      const next = { ...previous, [field]: value };
      if ((field === 'sgst' || field === 'cgst') && Number(value) > 0) {
        next.igst = 0;
      }
      if (field === 'igst' && Number(value) > 0) {
        next.sgst = 0;
        next.cgst = 0;
      }
      return next;
    });
    setItemErrors((previous) => ({ ...previous, [field]: '' }));
  };

  const addItem = () => {
    const errors = {};
    if (!itemForm.item_id) errors.item_name = 'Select an item.';
    if (!itemForm.hsn_code.trim()) errors.hsn_code = 'HSN code is required.';
    if (!itemForm.quantity || Number(itemForm.quantity) <= 0) errors.quantity = 'Enter a valid quantity.';
    if (itemForm.price === '' || Number(itemForm.price) < 0) errors.price = 'Enter a valid price.';

    if (Object.keys(errors).length) {
      setItemErrors(errors);
      return;
    }

    if (editingIndex === null) {
      setItems((previous) => {
        const duplicateIndex = previous.findIndex(
          (row) => Number(row.item_id) === Number(itemForm.item_id),
        );

        if (duplicateIndex === -1) {
          return [...previous, { ...itemForm, _rowId: ++rowCounter }];
        }

        return previous.map((row, index) => (
          index === duplicateIndex
            ? { ...itemForm, _rowId: row._rowId }
            : row
        ));
      });
    } else {
      setItems((previous) => previous.map((row, index) => (
        index === editingIndex ? { ...itemForm, _rowId: row._rowId } : row
      )));
    }

    // The entry form is cleared after every add. Existing rows remain in Transaction Items.
    setItemForm(createEmptyItem());
    setEditingIndex(null);
    setItemErrors({});
  };

  const clearAll = () => {
    setDetails(createEmptyDetails());
    setItemForm(createEmptyItem());
    setItems([]);
    setEditingIndex(null);
    setDetailErrors({});
    setItemErrors({});
  };

  const saveQuotation = () => {
    const errors = {};
    if (!details.customer_id) errors.customer_id = 'Customer is required.';
    if (!details.quotation_date) errors.quotation_date = 'Quotation date is required.';

    if (details.show_shipping_address_on_bill) {
      if (!details.ship_to.trim()) errors.ship_to = 'Ship To is required.';
      if (!details.ship_to_address.trim()) errors.ship_to_address = 'Ship To Address is required.';
      if (!details.ship_state) errors.ship_state = 'Shipping state is required.';
    }

    setDetailErrors(errors);
    if (Object.keys(errors).length) {
      toast.error('Please complete the required quotation details.');
      return;
    }
    if (!items.length) {
      toast.error('Add at least one item before saving.');
      return;
    }

    const payload = {
      quotation_no: details.quotation_no || null,
      order_no: details.order_no || null,
      customer_id: Number(details.customer_id),
      quotation_date: details.quotation_date,
      due_term: details.due_term === '' ? null : Number(details.due_term),
      due_date: details.due_date || null,
      is_gst: Boolean(details.is_gst),
            done_by: details.done_by || null,
      brokerage: Number(details.brokerage) || 0,
      broker_remarks: details.broker_remarks.trim() || null,
      address: details.address.trim() || null,
      city: details.city.trim() || null,
      state: details.customer_state || null,
      contact_no: details.contact_no.trim() || null,
      email: details.email.trim() || null,
      items: items.map((item) => ({
        item_id: Number(item.item_id),
        item_name: item.item_name,
        hsn_code: item.hsn_code,
        quantity: Number(item.quantity),
        unit: item.unit,
        price: Number(item.price),
        disc_percent: Number(item.disc_percent) || 0,
        sgst: details.is_gst ? Number(item.sgst) || 0 : 0,
        cgst: details.is_gst ? Number(item.cgst) || 0 : 0,
        igst: details.is_gst ? Number(item.igst) || 0 : 0,
      })),
      delivery_date: details.delivery_date || null,
      ship_to: details.ship_to.trim() || null,
      ship_to_address: details.ship_to_address.trim() || null,
      shipping_state: details.ship_state || null,
      transport: details.transport.trim() || null,
      reference: details.reference.trim() || null,
      remarks: details.remarks.trim() || null,
      show_shipping_address_on_bill: Boolean(details.show_shipping_address_on_bill),
    };

    setSaving(true);

    const request = editId
      ? updateQuotation(editId, payload)
      : createQuotation(payload);

    request
      .then((saved) => {
        if (editId) {
          toast.success(`Quotation updated. Quotation No. ${saved.quotation_no}`);
          navigate('/quotation-history');
          return null;
        }

        toast.success(`Quotation saved. Quotation No. ${saved.quotation_no}`);
        clearAll();
        return null;
      })
      .catch((error) => toast.error(extractErrorMessage(error)))
      .finally(() => setSaving(false));
  };

  return (
    <div className="page general-transaction purchase-entry-final" data-enter-navigation onKeyDown={handleEnterNavigation}>
      <header className="gt-page-header">
        <div>
          <h1>{editId ? 'Update Quotation' : 'Quotation Entry'}</h1>
          <p>{editId ? 'Update the selected quotation and its transaction items.' : 'Create and save a customer quotation as a preview before sale.'}</p>
        </div>
        <span className="gt-status">{editId ? 'Edit Quotation' : 'Quotation'}</span>
      </header>

      {loadingQuotation && (
        <div className="gt-loading-note">Loading quotation details...</div>
      )}

      <Card title="Transaction Details" className="gt-card">
        <div className="gt-details-grid">
          <div className="gt-with-action">
            <AccountSelector domain="customer" record={details._account}
              value={details.customer_id}
              onChange={selectCustomer}
              required
              error={detailErrors.customer_id}
            />
            <button
              type="button"
              className="gt-plus"
              onClick={() => {
                saveDraft(DRAFT_KEY, { details, items, itemForm });
                navigate('/customers?openAdd=1&returnTo=/quotation-entry');
              }}
              title="Add new customer"
              aria-label="Add new customer"
            >
              +
            </button>
          </div>

          <FormInput label="Quotation No." value={details.quotation_no} placeholder="Generated automatically" disabled />
          <FormInput label="Order No." value={details.order_no} placeholder="Generated automatically" disabled />
          <FormInput
            label="Quotation Date"
            type="date"
            value={details.quotation_date}
            onChange={(value) => changeDetail('quotation_date', value)}
            required
            error={detailErrors.quotation_date}
          />
          <FormInput
            label="Due Term (Days)"
            type="number"
            min="0"
            value={details.due_term}
            onChange={(value) => changeDetail('due_term', value)}
          />
          <FormInput label="Due Date" type="date" value={details.due_date} disabled />

          <FormTextarea label="Address" value={details.address} onChange={() => {}} rows={2} disabled />
          <FormInput label="City" value={details.city} onChange={() => {}} disabled />
          <FormSelect
            label="State"
            value={details.customer_state || ''}
            onChange={(value) => changeDetail('customer_state', value)}
            options={STATE_OPTIONS}
          />
          <FormInput label="Contact No." value={details.contact_no} onChange={() => {}} disabled />
          <FormInput label="Email" value={details.email} onChange={() => {}} disabled />
          <DoneBySelect
            label="Done By"
            value={details.done_by}
            onChange={(value) => changeDetail('done_by', value)}
            savedValue={details._savedDoneBy}
          />
          <FormCheckbox
            label="GST Applicable"
            checked={details.is_gst}
            onChange={(value) => changeDetail('is_gst', value)}
          />
          <FormInput
            label="Brokerage"
            type="number"
            min="0"
            value={details.brokerage}
            onChange={(value) => changeDetail('brokerage', value)}
          />
          <div className="gt-span-2">
            <FormInput
              label="Broker's Remarks"
              value={details.broker_remarks}
              onChange={(value) => changeDetail('broker_remarks', value)}
            />
          </div>
        </div>
      </Card>

      <Card title="Item Entry" className="gt-card">
        <div className="gt-item-top">
          <div className="gt-with-action">
            <SearchableSelect
              label="Item Name"
              options={itemOptions}
              value={itemForm.item_id}
              onChange={selectItem}
              placeholder="Search item name..."
              required
              error={itemErrors.item_name}
            />
            <button
              type="button"
              className="gt-plus"
              onClick={() => {
                saveDraft(DRAFT_KEY, { details, items, itemForm });
                navigate('/item-master?openAdd=1&returnTo=/quotation-entry');
              }}
              title="Add new item"
              aria-label="Add new item"
            >
              +
            </button>
          </div>
          <FormInput label="HSN Code" value={itemForm.hsn_code} onChange={() => {}} disabled required />
          <FormSelect
            label="Unit"
            value={itemForm.unit}
            onChange={() => {}}
            options={UNIT_OPTIONS}
            disabled
          />
        </div>

        <div className="gt-item-numbers sales-entry__item-numbers">
          <FormInput
            label="Quantity"
            type="number"
            min="0"
            value={itemForm.quantity}
            onChange={(value) => changeItem('quantity', value)}
            required
            error={itemErrors.quantity}
          />
          <FormInput
            label="Price"
            type="number"
            min="0"
            value={itemForm.price}
            onChange={(value) => changeItem('price', value)}
            required
            error={itemErrors.price}
          />
          <div className="sales-stock-box">
            <span>Current Stock</span>
            <strong>{itemForm.item_id ? itemForm.current_stock : '—'}</strong>
          </div>
          <FormInput label="Discount %" type="number" min="0" max="100" value={itemForm.disc_percent} onChange={(value) => changeItem('disc_percent', value)} />
          <FormInput label="SGST %" type="number" min="0" max="100" value={details.is_gst ? itemForm.sgst : 0} onChange={(value) => changeItem('sgst', value)} disabled={!details.is_gst || Number(itemForm.igst) > 0} />
          <FormInput label="CGST %" type="number" min="0" max="100" value={details.is_gst ? itemForm.cgst : 0} onChange={(value) => changeItem('cgst', value)} disabled={!details.is_gst || Number(itemForm.igst) > 0} />
          <FormInput label="IGST %" type="number" min="0" max="100" value={details.is_gst ? itemForm.igst : 0} onChange={(value) => changeItem('igst', value)} disabled={!details.is_gst || Number(itemForm.sgst) > 0 || Number(itemForm.cgst) > 0} />
          <div className="gt-live-amount"><span>Amount</span><strong>{formatCurrency(liveAmount)}</strong></div>
        </div>

        <div className="gt-item-actions">
          <Button variant="secondary" onClick={() => { setItemForm(createEmptyItem()); setEditingIndex(null); }}>Clear</Button>
          <Button variant="primary" onClick={addItem}>{editingIndex === null ? 'Add Item' : 'Update Item'}</Button>
        </div>
      </Card>

      <Card title="Transaction Items" className="gt-card">
        <div className="gt-table-wrap">
          <table className="gt-table">
            <thead>
              <tr>
                <th>Sr.</th><th>Item</th><th>HSN</th><th>Qty</th><th>Unit</th>
                <th>Price</th><th>Disc.</th><th>SGST</th><th>CGST</th><th>IGST</th>
                <th>Amount</th><th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {!items.length ? (
                <tr><td colSpan="12" className="gt-empty">No items added yet.</td></tr>
              ) : items.map((row, index) => (
                <tr key={row._rowId}>
                  <td>{index + 1}</td><td>{row.item_name}</td><td>{row.hsn_code}</td>
                  <td>{row.quantity}</td><td>{row.unit}</td><td>{formatCurrency(row.price)}</td>
                  <td>{row.disc_percent}%</td>
                  <td>{details.is_gst ? row.sgst : 0}%</td>
                  <td>{details.is_gst ? row.cgst : 0}%</td>
                  <td>{details.is_gst ? row.igst : 0}%</td>
                  <td>
                    {formatCurrency(
                      computeLineAmounts(
                        details.is_gst
                          ? row
                          : { ...row, sgst: 0, cgst: 0, igst: 0 },
                      ).amount,
                    )}
                  </td>
                  <td>
                    <button type="button" className="gt-link" onClick={() => { setItemForm(row); setEditingIndex(index); }}>Edit</button>
                    <button type="button" className="gt-link gt-link--danger" onClick={() => setItems((previous) => previous.filter((_, rowIndex) => rowIndex !== index))}>Delete</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </Card>

      <div className="gt-bottom-grid">
        <Card title="Extra Address & Delivery Details" className="gt-card">
          <FormCheckbox
            label="Show this shipping address on bill"
            checked={details.show_shipping_address_on_bill}
            onChange={(value) => changeDetail('show_shipping_address_on_bill', value)}
          />
          <div className="gt-delivery-grid">
            <FormInput label="Delivery Date" type="date" min={today()} value={details.delivery_date} onChange={(value) => changeDetail('delivery_date', value)} />
            <FormInput label="Ship To" value={details.ship_to} onChange={(value) => changeDetail('ship_to', value)} required={details.show_shipping_address_on_bill} error={detailErrors.ship_to} />
            <FormInput label="Transport" value={details.transport} onChange={(value) => changeDetail('transport', value)} />
            <div className="gt-span-2">
              <FormTextarea label="Ship To Address" value={details.ship_to_address} onChange={(value) => changeDetail('ship_to_address', value)} rows={3} required={details.show_shipping_address_on_bill} error={detailErrors.ship_to_address} />
            </div>
            <FormSelect label="State" value={details.ship_state} onChange={(value) => changeDetail('ship_state', value)} options={STATE_OPTIONS} required={details.show_shipping_address_on_bill} error={detailErrors.ship_state} />
            <FormInput label="Reference" value={details.reference} onChange={(value) => changeDetail('reference', value)} />
            <div className="gt-span-2"><FormTextarea label="Remarks" value={details.remarks} onChange={(value) => changeDetail('remarks', value)} rows={3} /></div>
          </div>
        </Card>

        <Card title="Total Summary" className="gt-card gt-summary">
          <div><span>Taxable Amount</span><strong>{formatCurrency(totals.taxableAmount)}</strong></div>
          <div><span>SGST Total</span><strong>{formatCurrency(totals.sgstTotal)}</strong></div>
          <div><span>CGST Total</span><strong>{formatCurrency(totals.cgstTotal)}</strong></div>
          <div><span>IGST Total</span><strong>{formatCurrency(totals.igstTotal)}</strong></div>
          <div className="gt-grand"><span>Grand Total</span><strong>{formatCurrency(totals.grandTotal)}</strong></div>
        </Card>
      </div>

      <div className="gt-footer-actions">
        <Button variant="secondary" onClick={clearAll} disabled={saving}>Clear</Button>
        <Button variant="primary" onClick={saveQuotation} disabled={saving}>{saving
          ? (editId ? 'Updating Quotation...' : 'Saving Quotation...')
          : (editId ? 'Update Quotation' : 'Save Quotation')}</Button>
      </div>
    </div>
  );
}
